remote_theme: olivier3lanc/Jekyll-LibDoc
title: Gtyinstinct's homepage
description: Welcome to gtyinstinct's homepage

defaults:
  -
    values:
      layout: libdoc/page
kramdown:
    syntax_highlighter_opts:
        disable: true
sass:
    style: compressed